[package]
name = "wbaes-cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Command-line interface for generating and using white-box AES instances"

[dependencies]

[[bin]]
name = "wbaes"
path = "src/main.rs"
